/**
 * Given an array of n elements, all numbers,
 * return the largest sum that can be generated by a contiguous subarray.
 */

/* Accepted
 ** Runtime 147 ms - better than 15.25% of Javascript submissions
 ** Memory 50.2 MB - Better than 67.38% of Javascript submissions
 */
const maxSubArray = (nums) => {
  let sum = nums[0],
    max = nums[0];

  for (let i = 1; i < nums.length; i++) {
    sum += nums[i];

    if (nums[i] > sum) {
      sum = nums[i];
    }

    if (sum > max) {
      max = sum;
    }
  }

  return max;
};

console.log(maxSubArray([-2, 1, -3, 4, -1, 2, 1, -5, 4])); // 6
console.log(maxSubArray([1])); // 1
console.log(maxSubArray([5, 4, -1, 7, 8])); // 23
